"""Adapter for the shared Martelo V2 budget archive.

The V2 schema is discovered at runtime because installations in transition do
not all have exactly the same column names.  Reads remain broadly tolerant;
writes are deliberately narrow and fail closed when the price origin cannot be
proven to be manual.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import MetaData, Table, create_engine, event, inspect, select, update
from sqlalchemy.engine import Engine, URL


class V2ArquivoConfigError(RuntimeError):
    """The V2 connection is not configured."""


class V2ArquivoSchemaError(RuntimeError):
    """The connected V2 schema cannot be safely mapped."""


class V2ArquivoWriteError(RuntimeError):
    """A controlled V2 update could not be completed."""


class V2PrecoProtegidoError(V2ArquivoWriteError):
    """The final price is generated by costing and cannot be edited here."""


@dataclass(frozen=True)
class OrcamentoV2Resumo:
    numero: str
    versao: str
    cliente: str
    ref_cliente: str
    obra: str
    descricao: str
    estado: str
    data: date | datetime | str | None
    total: Decimal | float | str | None
    utilizador: str
    tabela_origem: str
    enc_phc: str = ""
    preco_manual: bool | None = None
    origem_preco: str = "desconhecida"
    chave: Any = None
    origem_preco_inferida: bool = False

    @property
    def preco_editavel(self) -> bool:
        """Whether V3 may change the final price for this row."""
        return self.origem_preco == "manual"


@dataclass(frozen=True)
class _V2Tabela:
    tabela: Table
    mapa: dict[str, str]


ALIASES = {
    "id": ("id", "orcamento_id", "codigo_id"),
    "numero": ("num_orcamento", "numero_orcamento", "orcamento", "numero", "nr_orcamento"),
    "versao": ("versao", "numero_versao", "ver"),
    "cliente": ("cliente", "nome_cliente", "cliente_nome"),
    "ref_cliente": ("ref_cliente", "referencia_cliente", "refcli"),
    "obra": ("obra", "nome_obra"),
    "descricao": ("descricao", "descricao_orcamento", "descr", "observacoes"),
    "estado": ("estado", "status", "situacao"),
    "data": ("data", "data_orcamento", "created_at", "dt_orcamento"),
    "total": ("preco_total", "total", "valor_total", "valor"),
    "utilizador": ("utilizador", "username", "user", "criado_por"),
    "enc_phc": (
        "enc_phc",
        "num_enc_phc",
        "n_enc_phc",
        "enc_phc_num",
        "encomenda_phc",
        "num_encomenda_phc",
    ),
    "preco_manual": (
        "preco_manual",
        "preco_digitado",
        "preco_externo",
        "manual",
        "total_manual",
    ),
    "origem_preco": (
        "origem_preco",
        "tipo_preco",
        "metodo_preco",
        "preco_calculado_por",
    ),
}


def criar_engine_v2(*, read_only: bool = True) -> Engine:
    """Create a V2 engine with a session-level SQL safety guard."""
    url = os.getenv("V2_DATABASE_URL")
    if not url:
        user = os.getenv("V2_DB_USER")
        password = os.getenv("V2_DB_PASSWORD")
        if not user or not password:
            raise V2ArquivoConfigError(
                "Arquivo V2 não configurado. Defina V2_DB_USER e V2_DB_PASSWORD "
                "ou V2_DATABASE_URL."
            )
        url = URL.create(
            "mysql+pymysql",
            username=user,
            password=password,
            host=os.getenv("V2_DB_HOST", "192.168.5.201"),
            port=int(os.getenv("V2_DB_PORT", "3306")),
            database=os.getenv("V2_DB_NAME", "orcamentos_v2"),
            query={"charset": "utf8mb4"},
        )

    engine = create_engine(url, pool_pre_ping=True, future=True)
    if read_only and engine.dialect.name == "mysql":
        event.listen(engine, "connect", _ativar_sessao_readonly)
    event.listen(
        engine,
        "before_cursor_execute",
        _bloquear_escrita if read_only else _bloquear_operacoes_nao_controladas,
    )
    return engine


def criar_engine_v2_readonly() -> Engine:
    """Backward-compatible explicit read-only factory."""
    return criar_engine_v2(read_only=True)


def _ativar_sessao_readonly(dbapi_connection, _connection_record) -> None:
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("SET SESSION TRANSACTION READ ONLY")
    finally:
        cursor.close()


def _primeiro_comando(statement: str) -> str:
    return statement.lstrip().split(None, 1)[0].upper() if statement.strip() else ""


def _bloquear_escrita(
    _conn, _cursor, statement, _parameters, _context, _executemany
) -> None:
    """Block every non-read statement on the legacy read-only connection."""
    inicio = _primeiro_comando(statement)
    if inicio not in {"SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "WITH", "PRAGMA"}:
        raise PermissionError(
            f"Arquivo V2 é apenas de leitura; comando bloqueado: {inicio or '?'}"
        )


def _bloquear_operacoes_nao_controladas(
    _conn, _cursor, statement, _parameters, _context, _executemany
) -> None:
    """Allow SELECTs and UPDATEs only; inserts/deletes/schema changes stay blocked."""
    inicio = _primeiro_comando(statement)
    if inicio not in {
        "SELECT",
        "SHOW",
        "DESCRIBE",
        "DESC",
        "EXPLAIN",
        "WITH",
        "PRAGMA",
        "UPDATE",
    }:
        raise PermissionError(
            "Arquivo V2 só permite atualizações controladas; comando bloqueado: "
            f"{inicio or '?'}"
        )


class V2ArquivoService:
    """Discover, list and narrowly update budget headers in V2."""

    def __init__(self, engine: Engine) -> None:
        self.engine = engine

    def listar_orcamentos(self, *, limite: int = 500) -> list[OrcamentoV2Resumo]:
        contexto = self._carregar_tabela()
        tabela = contexto.tabela
        mapa = contexto.mapa
        if "numero" not in mapa:
            raise V2ArquivoSchemaError(
                f"A tabela V2 '{tabela.name}' não tem uma coluna reconhecida de número."
            )

        metadata = tabela.metadata
        tabelas_disponiveis = set(inspect(self.engine).get_table_names())
        from_clause = tabela
        colunas = [tabela]
        if "client_id" in tabela.c and "clients" in tabelas_disponiveis:
            clients = Table("clients", metadata, autoload_with=self.engine)
            if "id" in clients.c and "nome" in clients.c:
                from_clause = from_clause.outerjoin(
                    clients, tabela.c.client_id == clients.c.id
                )
                colunas.append(clients.c.nome.label("__cliente_nome"))
        if "created_by" in tabela.c and "users" in tabelas_disponiveis:
            users = Table("users", metadata, autoload_with=self.engine)
            if "id" in users.c and "username" in users.c:
                from_clause = from_clause.outerjoin(
                    users, tabela.c.created_by == users.c.id
                )
                colunas.append(users.c.username.label("__utilizador_nome"))

        stmt = select(*colunas).select_from(from_clause).limit(
            max(1, min(int(limite), 5000))
        )
        if "data" in mapa:
            stmt = stmt.order_by(tabela.c[mapa["data"]].desc())
        with self.engine.connect() as connection:
            rows = connection.execute(stmt).mappings().all()
            ids_com_items = self._ids_com_items(connection, contexto, rows)
        return [self._adaptar(row, contexto, ids_com_items) for row in rows]

    def atualizar_orcamento(
        self,
        item: OrcamentoV2Resumo,
        *,
        estado: str,
        enc_phc: str | None,
        total: Decimal | None,
    ) -> None:
        """Update state/ENC and, only when proven manual, the final price.

        The original values are included in the WHERE clause so a simultaneous
        edit in V2 is detected instead of silently overwritten by V3.
        """
        estado = (estado or "").strip()
        if not estado:
            raise ValueError("O estado é obrigatório.")
        if not item.preco_editavel and total != _to_decimal(item.total):
            raise V2PrecoProtegidoError(
                "O preço deste orçamento vem do custeio. Abra o orçamento no V2 "
                "para alterar os items e recalcular o preço final."
            )

        contexto = self._carregar_tabela()
        tabela = contexto.tabela
        mapa = contexto.mapa
        for campo in ("estado", "enc_phc"):
            if campo not in mapa:
                raise V2ArquivoSchemaError(
                    f"A tabela V2 não tem a coluna necessária para '{campo}'."
                )
        if total != _to_decimal(item.total) and "total" not in mapa:
            raise V2ArquivoSchemaError(
                "A tabela V2 não tem uma coluna reconhecida para o preço total."
            )

        identidade = self._condicao_identidade(tabela, mapa, item)
        if identidade is None:
            raise V2ArquivoSchemaError(
                "Não foi possível identificar univocamente o orçamento V2."
            )
        condicao = identidade
        condicao = condicao & self._condicao_igual(
            tabela.c[mapa["estado"]], item.estado
        )
        condicao = condicao & self._condicao_igual(
            tabela.c[mapa["enc_phc"]], item.enc_phc or None
        )
        if "total" in mapa:
            condicao = condicao & self._condicao_igual(
                tabela.c[mapa["total"]], _to_decimal(item.total)
            )

        valores: dict[str, Any] = {
            mapa["estado"]: estado,
            mapa["enc_phc"]: (enc_phc or None),
        }
        if total != _to_decimal(item.total):
            if not item.preco_editavel:
                raise V2PrecoProtegidoError(
                    "Preço protegido: a origem indicada é o custeio."
                )
            valores[mapa["total"]] = total

        with self.engine.begin() as connection:
            result = connection.execute(update(tabela).where(condicao).values(valores))
            if result.rowcount != 1:
                raise V2ArquivoWriteError(
                    "O orçamento mudou entretanto no V2. Atualize a lista e tente novamente."
                )

    def _carregar_tabela(self) -> _V2Tabela:
        insp = inspect(self.engine)
        tabela_nome = self._escolher_tabela(insp.get_table_names())
        metadata = MetaData()
        tabela = Table(tabela_nome, metadata, autoload_with=self.engine)
        return _V2Tabela(tabela=tabela, mapa=self._mapear_colunas(tabela))

    @staticmethod
    def _escolher_tabela(tabelas: list[str]) -> str:
        candidatas = [t for t in tabelas if "orc" in t.casefold()]
        preferidas = (
            "orcamentos",
            "orcamento",
            "orcamentos_cabecalho",
            "orcamento_cabecalho",
        )
        por_nome = {t.casefold(): t for t in candidatas}
        for nome in preferidas:
            if nome in por_nome:
                return por_nome[nome]
        if candidatas:
            return sorted(candidatas, key=lambda t: ("item" in t.casefold(), len(t)))[0]
        raise V2ArquivoSchemaError(
            "Não foi encontrada nenhuma tabela de orçamentos na base V2."
        )

    @staticmethod
    def _mapear_colunas(tabela: Table) -> dict[str, str]:
        existentes = {col.name.casefold(): col.name for col in tabela.columns}
        mapa: dict[str, str] = {}
        for destino, aliases in ALIASES.items():
            for alias in aliases:
                if alias.casefold() in existentes:
                    mapa[destino] = existentes[alias.casefold()]
                    break
        return mapa

    @classmethod
    def _adaptar(
        cls,
        row,
        contexto: _V2Tabela,
        ids_com_items: set[Any] | None = None,
    ) -> OrcamentoV2Resumo:
        mapa = contexto.mapa

        def valor(chave, default=""):
            coluna = mapa.get(chave)
            dado = row.get(coluna) if coluna else default
            return default if dado is None else dado

        origem, manual, inferida = cls._resolver_origem_preco(
            row,
            mapa,
            tem_items=(valor("id", None) in (ids_com_items or set())),
        )
        return OrcamentoV2Resumo(
            numero=str(valor("numero")),
            versao=str(valor("versao")),
            cliente=str(row.get("__cliente_nome") or valor("cliente")),
            ref_cliente=str(valor("ref_cliente")),
            obra=str(valor("obra")),
            descricao=str(valor("descricao")),
            estado=str(valor("estado")),
            data=valor("data", None),
            total=valor("total", None),
            utilizador=str(row.get("__utilizador_nome") or valor("utilizador")),
            tabela_origem=contexto.tabela.name,
            enc_phc=str(valor("enc_phc")),
            preco_manual=manual,
            origem_preco=origem,
            chave=valor("id", None) or (str(valor("numero")), str(valor("versao"))),
            origem_preco_inferida=inferida,
        )

    @staticmethod
    def _resolver_origem_preco(
        row,
        mapa: dict[str, str],
        *,
        tem_items: bool,
    ) -> tuple[str, bool | None, bool]:
        coluna_origem = mapa.get("origem_preco")
        texto_origem = str(row.get(coluna_origem) or "").casefold() if coluna_origem else ""
        if any(valor in texto_origem for valor in ("manual", "extern", "digit", "fonte")):
            return "manual", True, False
        if any(valor in texto_origem for valor in ("custeio", "item", "calcul", "formula")):
            return "custeio", False, False

        coluna_manual = mapa.get("preco_manual")
        if coluna_manual:
            raw = row.get(coluna_manual)
            if isinstance(raw, str):
                normalizado = raw.strip().casefold()
                if normalizado in {"1", "true", "yes", "sim", "manual"}:
                    return "manual", True, False
                if normalizado in {"0", "false", "no", "nao", "não", "custeio"}:
                    return "custeio", False, False
            if raw is not None:
                return (("manual", True, False) if bool(raw) else ("custeio", False, False))

        # The live V2 schema currently has no explicit flag in ``orcamentos``.
        # During the transition, the conservative fallback is: rows with
        # costing items are protected; a header-only total is treated as an
        # external/manual price.  Unknown empty rows remain blocked.
        if tem_items:
            return "custeio", False, True
        if mapa.get("total") and row.get(mapa["total"]) is not None:
            return "manual", True, True
        return "desconhecida", None, True

    def _ids_com_items(
        self,
        connection,
        contexto: _V2Tabela,
        rows,
    ) -> set[Any]:
        """Return V2 budget ids that have item rows, when that table exists."""
        if "id" not in contexto.mapa:
            return set()
        tabelas = set(inspect(self.engine).get_table_names())
        nome_items = next(
            (nome for nome in ("orcamento_items", "orcamentos_items") if nome in tabelas),
            None,
        )
        if nome_items is None:
            return set()
        items = Table(nome_items, contexto.tabela.metadata, autoload_with=self.engine)
        fk = next(
            (nome for nome in ("id_orcamento", "orcamento_id", "id_orcamento_fk") if nome in items.c),
            None,
        )
        if fk is None:
            return set()
        ids = [row.get(contexto.mapa["id"]) for row in rows]
        ids = [valor for valor in ids if valor is not None]
        if not ids:
            return set()
        statement = select(items.c[fk]).where(items.c[fk].in_(ids)).distinct()
        return set(connection.execute(statement).scalars().all())

    @staticmethod
    def _condicao_identidade(tabela: Table, mapa: dict[str, str], item: OrcamentoV2Resumo):
        if "id" in mapa and item.chave is not None and not isinstance(item.chave, tuple):
            return tabela.c[mapa["id"]] == item.chave
        if "numero" not in mapa or "versao" not in mapa:
            return None
        return (tabela.c[mapa["numero"]] == item.numero) & (
            tabela.c[mapa["versao"]] == item.versao
        )

    @staticmethod
    def _condicao_igual(coluna, valor):
        return coluna.is_(None) if valor is None else coluna == valor


def _to_decimal(value: Any) -> Decimal | None:
    if value is None or value == "":
        return None
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value).replace(",", ".").replace("€", "").strip())
    except (ArithmeticError, ValueError):
        return None
