"""Adapter for the shared Martelo V2 budget archive.

The V2 schema is discovered at runtime because installations in transition do
not all have exactly the same column names.  Reads remain broadly tolerant;
writes are deliberately narrow and fail closed when the price origin cannot be
proven to be manual.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import MetaData, Table, create_engine, event, inspect, select, update
from sqlalchemy.engine import Engine, URL
from sqlalchemy.exc import SQLAlchemyError

from app.db.session import credenciais_da_sessao


class V2ArquivoConfigError(RuntimeError):
    """The V2 connection is not configured."""


class V2ArquivoSchemaError(RuntimeError):
    """The connected V2 schema cannot be safely mapped."""


class V2ArquivoWriteError(RuntimeError):
    """A controlled V2 update could not be completed."""


class V2PrecoProtegidoError(V2ArquivoWriteError):
    """The final price is generated by costing and cannot be edited here."""


def cliente_temporario_do_extras(extras: Any) -> tuple[int | None, str]:
    """O cliente temporário guardado no ``extras`` de um orçamento do V2.

    O V2 não tem coluna para clientes temporários: quando o orçamento é para um
    cliente que ainda não está no PHC, o ``client_id`` fica a apontar para o
    registo genérico "CONSUMIDOR FINAL" e o cliente verdadeiro vai para o
    ``extras``, em JSON::

        {"preco_manual": true, "temp_client_id": 20,
         "temp_client_nome": "DSTCARPINTARIA"}

    Sem ler isto, o Arquivo V2 mostrava "CONSUMIDOR FINAL" em vez do cliente — e
    não era um caso ou outro: são 104 orçamentos, TODOS os que apareciam como
    consumidor final. Nenhum deles é mesmo consumidor final.

    Devolve ``(id, nome)``; o nome é o que ficou gravado no orçamento e serve de
    salvaguarda quando o cliente temporário já foi apagado da tabela.
    """
    if isinstance(extras, (bytes, bytearray)):
        extras = extras.decode("utf-8", "replace")
    if isinstance(extras, str):
        try:
            extras = json.loads(extras)
        except (ValueError, TypeError):
            return None, ""
    if not isinstance(extras, dict):
        return None, ""

    bruto = extras.get("temp_client_id")
    try:
        temp_id = int(bruto) if bruto not in (None, "") else None
    except (TypeError, ValueError):
        temp_id = None

    return temp_id, str(extras.get("temp_client_nome") or "").strip()


def escolher_nome_do_cliente(
    *,
    nome_phc: str,
    temp_id: int | None,
    temp_nome: str,
    temporarios: dict[int, str] | None = None,
) -> tuple[str, bool]:
    """O nome a mostrar na coluna Cliente, e se é um cliente temporário.

    O cliente temporário ganha ao ``client_id``, porque nestes orçamentos o
    ``client_id`` é só o lugar-comum "CONSUMIDOR FINAL". Prefere-se o nome da
    tabela ``clientes_temporarios`` (é o nome por extenso — "HELICA GROUND
    SOLUTIONS LDA") e não o que ficou no orçamento (a forma curta, "HELICA"),
    para a coluna ficar igual à dos clientes do PHC, que também mostra o nome
    por extenso.
    """
    da_tabela = (temporarios or {}).get(temp_id, "") if temp_id is not None else ""
    nome_temporario = da_tabela or temp_nome
    if nome_temporario:
        return nome_temporario, True

    return nome_phc, False


@dataclass(frozen=True)
class OrcamentoV2Resumo:
    numero: str
    versao: str
    cliente: str
    ref_cliente: str
    obra: str
    descricao: str
    estado: str
    data: date | datetime | str | None
    total: Decimal | float | str | None
    utilizador: str
    tabela_origem: str
    enc_phc: str = ""
    preco_manual: bool | None = None
    origem_preco: str = "desconhecida"
    chave: Any = None
    origem_preco_inferida: bool = False
    #: O cliente veio da tabela de clientes TEMPORÁRIOS do V2 (não do PHC).
    cliente_temporario: bool = False

    @property
    def preco_editavel(self) -> bool:
        """Whether V3 may change the final price for this row."""
        return self.origem_preco == "manual"


@dataclass(frozen=True)
class _V2Tabela:
    tabela: Table
    mapa: dict[str, str]


ALIASES = {
    "id": ("id", "orcamento_id", "codigo_id"),
    "numero": ("num_orcamento", "numero_orcamento", "orcamento", "numero", "nr_orcamento"),
    "versao": ("versao", "numero_versao", "ver"),
    "cliente": ("cliente", "nome_cliente", "cliente_nome"),
    "ref_cliente": ("ref_cliente", "referencia_cliente", "refcli"),
    "obra": ("obra", "nome_obra"),
    "descricao": ("descricao", "descricao_orcamento", "descr", "observacoes"),
    "estado": ("estado", "status", "situacao"),
    "data": ("data", "data_orcamento", "created_at", "dt_orcamento"),
    "total": ("preco_total", "total", "valor_total", "valor"),
    "utilizador": ("utilizador", "username", "user", "criado_por"),
    "enc_phc": (
        "enc_phc",
        "num_enc_phc",
        "n_enc_phc",
        "enc_phc_num",
        "encomenda_phc",
        "num_encomenda_phc",
    ),
    "preco_manual": (
        "preco_manual",
        "preco_digitado",
        "preco_externo",
        "manual",
        "total_manual",
    ),
    "origem_preco": (
        "origem_preco",
        "tipo_preco",
        "metodo_preco",
        "preco_calculado_por",
    ),
}


def criar_engine_v2(*, read_only: bool = True) -> Engine:
    """Create a V2 engine with a session-level SQL safety guard.

    A conta usada é, por esta ordem:

    1. ``V2_DATABASE_URL`` ou ``V2_DB_USER``/``V2_DB_PASSWORD``, se estiverem
       no ``.env`` — é assim na máquina de quem faz manutenção.
    2. **A conta com que a pessoa entrou no Martelo.** O arquivo do V2 vive no
       mesmo servidor MySQL, por isso não é preciso segunda password nenhuma:
       basta que essa conta tenha leitura no arquivo, o que se dá uma vez no
       servidor com ``deploy\\mysql_arquivo_v2.sql``.

    O ``.env`` que vai dentro do instalador não leva credenciais — se levasse a
    conta partilhada do arquivo, qualquer pessoa que abrisse o ficheiro ficava
    com ela.
    """
    url = os.getenv("V2_DATABASE_URL")
    if not url:
        user = os.getenv("V2_DB_USER")
        password = os.getenv("V2_DB_PASSWORD")
        host = os.getenv("V2_DB_HOST", "")
        porta = os.getenv("V2_DB_PORT", "")
        if not user or not password:
            atual = credenciais_da_sessao()
            if atual is None:
                raise V2ArquivoConfigError(
                    "Arquivo V2 indisponível: ainda não entrou no Martelo. "
                    "O arquivo é consultado com a conta com que entra na "
                    "aplicação."
                )
            user, password = atual.utilizador, atual.password
            # O arquivo está no mesmo servidor do Martelo. Seguir o servidor da
            # ligação em curso faz com que uma mudança de máquina (o servidor da
            # empresa, um dia) não deixe esta ligação para trás.
            host = host or atual.host
            porta = porta or str(atual.porta)
        url = URL.create(
            "mysql+pymysql",
            username=user,
            password=password,
            host=host or "192.168.5.201",
            port=int(porta or "3306"),
            database=os.getenv("V2_DB_NAME", "orcamentos_v2"),
            query={"charset": "utf8mb4"},
        )

    engine = create_engine(url, pool_pre_ping=True, future=True)
    if read_only and engine.dialect.name == "mysql":
        event.listen(engine, "connect", _ativar_sessao_readonly)
    event.listen(
        engine,
        "before_cursor_execute",
        _bloquear_escrita if read_only else _bloquear_operacoes_nao_controladas,
    )
    return engine


#: Erros do MySQL que querem dizer "esta conta não chega lá", e não "a rede
#: falhou": 1044/1045 acesso negado, 1142/1143 falta privilégio na tabela ou
#: coluna, 1698 plugin de autenticação.
_ERROS_SEM_ACESSO = (1044, 1045, 1142, 1143, 1698)


def explicar_erro_v2(exc: Exception, *, ao_gravar: bool = False) -> str:
    """Traduz a falha para uma frase que se percebe sem saber SQL.

    "Confirme rede, servidor e credenciais" servia para tudo e não ajudava em
    nada. O caso comum tem nome: a conta da pessoa ainda não tem acesso ao
    arquivo — coisa que se resolve uma vez, no servidor.
    """
    original = getattr(exc, "orig", None)
    argumentos = getattr(original, "args", ()) or ()
    codigo = argumentos[0] if argumentos and isinstance(argumentos[0], int) else None
    if codigo in _ERROS_SEM_ACESSO:
        return (
            "A sua conta ainda não tem acesso ao Arquivo V2.\n\n"
            "Os orçamentos antigos vivem noutra base de dados ('orcamentos_v2'), "
            "no mesmo servidor. Quem faz a manutenção do Martelo tem de correr "
            "uma vez o ficheiro deploy\\mysql_arquivo_v2.sql para dar acesso a "
            "toda a gente."
        )
    if ao_gravar:
        return "Não foi possível gravar a alteração na base V2."
    return (
        "Não foi possível consultar a base V2. "
        "Confirme que o servidor está ligado e que tem rede."
    )


def criar_engine_v2_readonly() -> Engine:
    """Backward-compatible explicit read-only factory."""
    return criar_engine_v2(read_only=True)


def _ativar_sessao_readonly(dbapi_connection, _connection_record) -> None:
    cursor = dbapi_connection.cursor()
    try:
        cursor.execute("SET SESSION TRANSACTION READ ONLY")
    finally:
        cursor.close()


def _primeiro_comando(statement: str) -> str:
    return statement.lstrip().split(None, 1)[0].upper() if statement.strip() else ""


def _bloquear_escrita(
    _conn, _cursor, statement, _parameters, _context, _executemany
) -> None:
    """Block every non-read statement on the legacy read-only connection."""
    inicio = _primeiro_comando(statement)
    if inicio not in {"SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "WITH", "PRAGMA"}:
        raise PermissionError(
            f"Arquivo V2 é apenas de leitura; comando bloqueado: {inicio or '?'}"
        )


def _bloquear_operacoes_nao_controladas(
    _conn, _cursor, statement, _parameters, _context, _executemany
) -> None:
    """Allow SELECTs and UPDATEs only; inserts/deletes/schema changes stay blocked."""
    inicio = _primeiro_comando(statement)
    if inicio not in {
        "SELECT",
        "SHOW",
        "DESCRIBE",
        "DESC",
        "EXPLAIN",
        "WITH",
        "PRAGMA",
        "UPDATE",
    }:
        raise PermissionError(
            "Arquivo V2 só permite atualizações controladas; comando bloqueado: "
            f"{inicio or '?'}"
        )


class V2ArquivoService:
    """Discover, list and narrowly update budget headers in V2."""

    def __init__(self, engine: Engine) -> None:
        self.engine = engine

    def listar_orcamentos(self, *, limite: int = 500) -> list[OrcamentoV2Resumo]:
        contexto = self._carregar_tabela()
        tabela = contexto.tabela
        mapa = contexto.mapa
        if "numero" not in mapa:
            raise V2ArquivoSchemaError(
                f"A tabela V2 '{tabela.name}' não tem uma coluna reconhecida de número."
            )

        metadata = tabela.metadata
        tabelas_disponiveis = set(inspect(self.engine).get_table_names())
        from_clause = tabela
        colunas = [tabela]
        # As duas juncoes seguintes sao um extra: dao o NOME do cliente e de
        # quem criou. Se a conta nao chegar a essas tabelas, mostra-se a lista
        # sem esses nomes -- perder uma coluna e' muito melhor do que perder o
        # arquivo inteiro por causa de um privilegio a menos.
        if "client_id" in tabela.c and "clients" in tabelas_disponiveis:
            clients = self._refletir_opcional("clients", metadata)
            if clients is not None and "id" in clients.c and "nome" in clients.c:
                from_clause = from_clause.outerjoin(
                    clients, tabela.c.client_id == clients.c.id
                )
                colunas.append(clients.c.nome.label("__cliente_nome"))
        if "created_by" in tabela.c and "users" in tabelas_disponiveis:
            users = self._refletir_opcional("users", metadata)
            if users is not None and "id" in users.c and "username" in users.c:
                from_clause = from_clause.outerjoin(
                    users, tabela.c.created_by == users.c.id
                )
                colunas.append(users.c.username.label("__utilizador_nome"))

        stmt = select(*colunas).select_from(from_clause).limit(
            max(1, min(int(limite), 5000))
        )
        if "data" in mapa:
            stmt = stmt.order_by(tabela.c[mapa["data"]].desc())
        with self.engine.connect() as connection:
            rows = connection.execute(stmt).mappings().all()
            ids_com_items = self._ids_com_items(connection, contexto, rows)
            temporarios = self._clientes_temporarios(
                connection, metadata, tabelas_disponiveis
            )
        return [
            self._adaptar(row, contexto, ids_com_items, temporarios) for row in rows
        ]

    def _clientes_temporarios(
        self, connection, metadata: MetaData, tabelas_disponiveis: set[str]
    ) -> dict[int, str]:
        """Os clientes temporários do V2, por id (são poucas dezenas).

        Uma consulta só, à parte: o cliente temporário está referido dentro do
        JSON do ``extras`` de cada orçamento, e juntar tabelas por um campo que
        vive dentro de um JSON dependia da versão do MySQL. Ler a tabela inteira
        de uma vez é mais simples e não engana ninguém.

        Se a conta não chegar à tabela, devolve vazio: cai-se no nome que ficou
        gravado no próprio orçamento, que é a salvaguarda.
        """
        if "clientes_temporarios" not in tabelas_disponiveis:
            return {}

        tabela = self._refletir_opcional("clientes_temporarios", metadata)
        if tabela is None or "id" not in tabela.c or "nome" not in tabela.c:
            return {}

        try:
            linhas = connection.execute(
                select(tabela.c.id, tabela.c.nome)
            ).all()
        except SQLAlchemyError:
            return {}

        return {
            int(linha_id): str(nome).strip()
            for linha_id, nome in linhas
            if linha_id is not None and str(nome or "").strip()
        }

    def atualizar_orcamento(
        self,
        item: OrcamentoV2Resumo,
        *,
        estado: str,
        enc_phc: str | None,
        total: Decimal | None,
    ) -> None:
        """Update state/ENC and, only when proven manual, the final price.

        The original values are included in the WHERE clause so a simultaneous
        edit in V2 is detected instead of silently overwritten by V3.
        """
        estado = (estado or "").strip()
        if not estado:
            raise ValueError("O estado é obrigatório.")
        if not item.preco_editavel and total != _to_decimal(item.total):
            raise V2PrecoProtegidoError(
                "O preço deste orçamento vem do custeio. Abra o orçamento no V2 "
                "para alterar os items e recalcular o preço final."
            )

        contexto = self._carregar_tabela()
        tabela = contexto.tabela
        mapa = contexto.mapa
        for campo in ("estado", "enc_phc"):
            if campo not in mapa:
                raise V2ArquivoSchemaError(
                    f"A tabela V2 não tem a coluna necessária para '{campo}'."
                )
        if total != _to_decimal(item.total) and "total" not in mapa:
            raise V2ArquivoSchemaError(
                "A tabela V2 não tem uma coluna reconhecida para o preço total."
            )

        identidade = self._condicao_identidade(tabela, mapa, item)
        if identidade is None:
            raise V2ArquivoSchemaError(
                "Não foi possível identificar univocamente o orçamento V2."
            )
        condicao = identidade
        condicao = condicao & self._condicao_igual(
            tabela.c[mapa["estado"]], item.estado
        )
        condicao = condicao & self._condicao_igual(
            tabela.c[mapa["enc_phc"]], item.enc_phc or None
        )
        if "total" in mapa:
            condicao = condicao & self._condicao_igual(
                tabela.c[mapa["total"]], _to_decimal(item.total)
            )

        valores: dict[str, Any] = {
            mapa["estado"]: estado,
            mapa["enc_phc"]: (enc_phc or None),
        }
        if total != _to_decimal(item.total):
            if not item.preco_editavel:
                raise V2PrecoProtegidoError(
                    "Preço protegido: a origem indicada é o custeio."
                )
            valores[mapa["total"]] = total

        with self.engine.begin() as connection:
            result = connection.execute(update(tabela).where(condicao).values(valores))
            if result.rowcount != 1:
                raise V2ArquivoWriteError(
                    "O orçamento mudou entretanto no V2. Atualize a lista e tente novamente."
                )

    def _refletir_opcional(self, nome: str, metadata: MetaData) -> Table | None:
        """Le a estrutura de uma tabela acessoria, ou devolve ``None``.

        A tabela ``users`` do V2 guarda as passwords, por isso no servidor so'
        se da acesso a`s colunas ``id`` e ``username``. Se um dia esse acesso
        nao existir de todo, isto devolve ``None`` em vez de rebentar.
        """
        try:
            return Table(nome, metadata, autoload_with=self.engine)
        except SQLAlchemyError:
            return None

    def _carregar_tabela(self) -> _V2Tabela:
        insp = inspect(self.engine)
        tabela_nome = self._escolher_tabela(insp.get_table_names())
        metadata = MetaData()
        tabela = Table(tabela_nome, metadata, autoload_with=self.engine)
        return _V2Tabela(tabela=tabela, mapa=self._mapear_colunas(tabela))

    @staticmethod
    def _escolher_tabela(tabelas: list[str]) -> str:
        candidatas = [t for t in tabelas if "orc" in t.casefold()]
        preferidas = (
            "orcamentos",
            "orcamento",
            "orcamentos_cabecalho",
            "orcamento_cabecalho",
        )
        por_nome = {t.casefold(): t for t in candidatas}
        for nome in preferidas:
            if nome in por_nome:
                return por_nome[nome]
        if candidatas:
            return sorted(candidatas, key=lambda t: ("item" in t.casefold(), len(t)))[0]
        raise V2ArquivoSchemaError(
            "Não foi encontrada nenhuma tabela de orçamentos na base V2."
        )

    @staticmethod
    def _mapear_colunas(tabela: Table) -> dict[str, str]:
        existentes = {col.name.casefold(): col.name for col in tabela.columns}
        mapa: dict[str, str] = {}
        for destino, aliases in ALIASES.items():
            for alias in aliases:
                if alias.casefold() in existentes:
                    mapa[destino] = existentes[alias.casefold()]
                    break
        return mapa

    @classmethod
    def _adaptar(
        cls,
        row,
        contexto: _V2Tabela,
        ids_com_items: set[Any] | None = None,
        temporarios: dict[int, str] | None = None,
    ) -> OrcamentoV2Resumo:
        mapa = contexto.mapa

        def valor(chave, default=""):
            coluna = mapa.get(chave)
            dado = row.get(coluna) if coluna else default
            return default if dado is None else dado

        origem, manual, inferida = cls._resolver_origem_preco(
            row,
            mapa,
            tem_items=(valor("id", None) in (ids_com_items or set())),
        )
        temp_id, temp_nome = cliente_temporario_do_extras(row.get("extras"))
        cliente, e_temporario = escolher_nome_do_cliente(
            nome_phc=str(row.get("__cliente_nome") or valor("cliente")),
            temp_id=temp_id,
            temp_nome=temp_nome,
            temporarios=temporarios,
        )

        return OrcamentoV2Resumo(
            numero=str(valor("numero")),
            versao=str(valor("versao")),
            cliente=cliente,
            ref_cliente=str(valor("ref_cliente")),
            obra=str(valor("obra")),
            descricao=str(valor("descricao")),
            estado=str(valor("estado")),
            data=valor("data", None),
            total=valor("total", None),
            utilizador=str(row.get("__utilizador_nome") or valor("utilizador")),
            tabela_origem=contexto.tabela.name,
            enc_phc=str(valor("enc_phc")),
            preco_manual=manual,
            origem_preco=origem,
            chave=valor("id", None) or (str(valor("numero")), str(valor("versao"))),
            origem_preco_inferida=inferida,
            cliente_temporario=e_temporario,
        )

    @staticmethod
    def _resolver_origem_preco(
        row,
        mapa: dict[str, str],
        *,
        tem_items: bool,
    ) -> tuple[str, bool | None, bool]:
        coluna_origem = mapa.get("origem_preco")
        texto_origem = str(row.get(coluna_origem) or "").casefold() if coluna_origem else ""
        if any(valor in texto_origem for valor in ("manual", "extern", "digit", "fonte")):
            return "manual", True, False
        if any(valor in texto_origem for valor in ("custeio", "item", "calcul", "formula")):
            return "custeio", False, False

        coluna_manual = mapa.get("preco_manual")
        if coluna_manual:
            raw = row.get(coluna_manual)
            if isinstance(raw, str):
                normalizado = raw.strip().casefold()
                if normalizado in {"1", "true", "yes", "sim", "manual"}:
                    return "manual", True, False
                if normalizado in {"0", "false", "no", "nao", "não", "custeio"}:
                    return "custeio", False, False
            if raw is not None:
                return (("manual", True, False) if bool(raw) else ("custeio", False, False))

        # The live V2 schema currently has no explicit flag in ``orcamentos``.
        # During the transition, the conservative fallback is: rows with
        # costing items are protected; a header-only total is treated as an
        # external/manual price.  Unknown empty rows remain blocked.
        if tem_items:
            return "custeio", False, True
        if mapa.get("total") and row.get(mapa["total"]) is not None:
            return "manual", True, True
        return "desconhecida", None, True

    def _ids_com_items(
        self,
        connection,
        contexto: _V2Tabela,
        rows,
    ) -> set[Any]:
        """Return V2 budget ids that have item rows, when that table exists."""
        if "id" not in contexto.mapa:
            return set()
        tabelas = set(inspect(self.engine).get_table_names())
        nome_items = next(
            (nome for nome in ("orcamento_items", "orcamentos_items") if nome in tabelas),
            None,
        )
        if nome_items is None:
            return set()
        items = Table(nome_items, contexto.tabela.metadata, autoload_with=self.engine)
        fk = next(
            (nome for nome in ("id_orcamento", "orcamento_id", "id_orcamento_fk") if nome in items.c),
            None,
        )
        if fk is None:
            return set()
        ids = [row.get(contexto.mapa["id"]) for row in rows]
        ids = [valor for valor in ids if valor is not None]
        if not ids:
            return set()
        statement = select(items.c[fk]).where(items.c[fk].in_(ids)).distinct()
        return set(connection.execute(statement).scalars().all())

    @staticmethod
    def _condicao_identidade(tabela: Table, mapa: dict[str, str], item: OrcamentoV2Resumo):
        if "id" in mapa and item.chave is not None and not isinstance(item.chave, tuple):
            return tabela.c[mapa["id"]] == item.chave
        if "numero" not in mapa or "versao" not in mapa:
            return None
        return (tabela.c[mapa["numero"]] == item.numero) & (
            tabela.c[mapa["versao"]] == item.versao
        )

    @staticmethod
    def _condicao_igual(coluna, valor):
        return coluna.is_(None) if valor is None else coluna == valor


def _to_decimal(value: Any) -> Decimal | None:
    if value is None or value == "":
        return None
    if isinstance(value, Decimal):
        return value
    try:
        return Decimal(str(value).replace(",", ".").replace("€", "").strip())
    except (ArithmeticError, ValueError):
        return None
